name: metrics-exporter-playground

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile.production
    container_name: app
    environment:
      TZ: "Asia/Tokyo"
      PUSHGATEWAY_ENDPOINT: "http://pushgateway:9091"
    ports:
      - mode: ingress
        published: 8080
        target: 8080
        protocol: tcp
    privileged: true
    restart: always
    tty: true
    # volumes:
    #   - type: bind
    #     source: ./app
    #     target: /app
    #     bind:
    #       create_host_path: true
    # working_dir: /app

  prometheus:
    build:
      context: ./.docker/prometheus
      dockerfile: ./Dockerfile
    container_name: prometheus
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - mode: ingress
        target: 9090
        published: 9090
        protocol: tcp
    privileged: true
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./.docker/prometheus/prometheus.yaml
        target: /etc/prometheus/prometheus.yml
        bind:
          create_host_path: true

  pushgateway:
    build:
      context: ./.docker/pushgateway
      dockerfile: ./Dockerfile
    container_name: pushgateway
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - mode: ingress
        target: 9091
        published: 9091
        protocol: tcp
    privileged: true
    restart: always
    tty: true

  grafana:
    build:
      context: ./.docker/grafana
      dockerfile: ./Dockerfile
    container_name: grafana
    environment:
      TZ: "Asia/Tokyo"
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SECURITY_ADMIN_USER: admin
      GF_SERVER_DOMAIN: localhost
      GF_SERVER_HTTP_PORT: 3000
      GF_SERVER_PROTOCOL: http
    ports:
      - mode: ingress
        target: 3000
        published: 3000
        protocol: tcp
    privileged: true
    restart: always
    tty: true
