apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: playground
    includeTemplates: true
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 60.0.2
    releaseName: kube-prometheus-stack
    valuesFile: ./values.yaml
    namespace: monitoring
    includeCRDs: true
