global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "metrics-exporter-playground"

scrape_configs:
  - job_name: "app-scrape"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "app:8080"
  - job_name: "pushgateway"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "pushgateway:9091"
