global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: "app-scrape"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "app:8080"
