{
 "title": "Custom Metrics Samples",
 "time": { "from": "2024-05-17T03:08:15.774Z", "to": "2024-05-17T03:48:59.213Z" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "memory_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Push Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "push_count", "legendFormat": "__auto" }
   ]
  }
 ]
}