apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-exporter-sample
  namespace: sample
  labels:
    app: metrics-exporter-sample-pod
spec:
  selector:
    matchLabels:
      app: metrics-exporter-sample-app
  replicas: 3
  template:
    metadata:
      labels:
        app: metrics-exporter-sample-app
    spec:
      containers:
        - name: metrics-exporter-sample
          image: ren1007/metrics-exporter-playground-app:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.4"
            requests:
              memory: "256Mi"
              cpu: "0.2"
          ports:
            - containerPort: 8080
