apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: playground
    includeTemplates: true
resources:
  - ./configmap.yaml
  - ./deployment.yaml
  - ./namespace.yaml
  - ./service.yaml
  - ./servicemonitor.yaml
