apiVersion: v1
kind: Service
metadata:
  name: metrics-exporter-sample
  namespace: sample
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: metrics-exporter-sample
