apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-exporter-sample
  namespace: sample
  labels:
    prometheus: agent
spec:
  selector:
    matchLabels:
      app: metrics-exporter-sample
  endpoints:
    - port: http
      interval: 30s
  namespaceSelector:
    matchNames:
      - sample
