apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: prometheus-pushgateway
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus-pushgateway
    version: 2.7.1
    valuesFile: ./values.yaml
    namespace: monitoring
    includeCRDs: true
